Repository Tama-rb/vimate, pull requests merged in 2019-01, with the labels that each got.

#8 デバッグ用の定義をconfig配下のファイルに追加した
  config/environments/development.rb
Labels: :name_badge:その他, :rocket:レビュー完了

#13 UserモデルおよびGitHubログイン機能追加
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  app/views/users/index.html.erb
  config/initializers/omniauth.rb
  config/routes.rb
  db/migrate/20190121050426_create_users.rb
  db/migrate/20190121103040_add_column_to_user.rb
  db/schema.rb
Labels: :rocket:レビュー完了

#14 RuboCopとCircleCIの設定を追加した
  .circleci/config.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  config/initializers/omniauth.rb
Labels: :bouquet:その他, :rocket:レビュー完了
